name: CI pipeline

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with: { bundler-cache: true }

      - name: Run tests
        run: bundle exec rails test
